---
- name: Playbook
  hosts: all
  vars_files:
    - variables.yml
  tasks:
    - name: create dir if not exist and copy script
      ansible.builtin.import_tasks: tasks/copy_script.yml

    - name: create user and make required changes
      ansible.builtin.import_tasks: tasks/create_user.yml
    
    - name: Install all required packages
      ansible.builtin.import_tasks: tasks/install_packages.yml

    - name: install terraform cli
      ansible.builtin.import_tasks: tasks/install_terraform.yml
