- name: Install unzip if not present
  ansible.builtin.package:
    name: unzip
    state: present

- name: Download terraform zip
  ansible.builtin.get_url:
    url: "{{ terraform_url }}"
    dest: "/tmp"

- name: Unzip the downloaded file
  ansible.builtin.unarchive:
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: yes