- name: Install unzip if not present
  ansible.builtin.package:
    name: unzip
    state: present

- name: Download terraform zip
  ansible.builtin.get_url:
    url: "{{ terraform_url }}"
    dest: "/tmp"

- name: Unzip the downloaded file
  ansible.builtin.unarchive:
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ tf_install_path }}"
    remote_src: yes

- name: Make terraform binary executable
  ansible.builtin.file:
    path: "{{ tf_install_path }}/terraform"
    mode: '0755'

- name: Add terraform to PATH
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/velero.sh"
    line: 'export PATH=$PATH:{{ tf_install_path }}/terraform'
    create: true
    mode: "0755"